---
networks:
  skynet:
    external: true

services:
  freqtrade-dorel:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-dorel
    # user: "$UID:$GID"
    networks:
      skynet:
        ipv4_address: 172.22.0.50
    volumes:
      - "/home/cristian/Repositories/freqtrade/dorel:/freqtrade/user_data"
    ports:
      - "8085:8080"
    # Default command used when running `docker compose up`
    # download-data 
    # --userdir /freqtrade/user_data 
    # --config /freqtrade/user_data/config.json
    # --config /freqtrade/user_data/.secret_config.json
    # --pairs-file /freqtrade/user_data/data/binance/pairs.json 
    # --days 240 --trading-mode spot --exchange binance
    command: >

      trade 
      --userdir /freqtrade/user_data
      --config /freqtrade/user_data/config.json 
      --config /freqtrade/user_data/.secret_config.json 
      --strategy-path /freqtrade/user_data/strategies
      --strategy Strategy001_custom_exit  
      --logfile /freqtrade/user_data/logs/freqtrade.log 
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
  
  freqtrade-gigel:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-gigel
    # user: "$UID:$GID"
    networks:
      skynet:
        ipv4_address: 172.22.0.51
    volumes:
      - "/home/cristian/Repositories/freqtrade/gigel:/freqtrade/user_data"
    ports:
      - "8086:8080"
    # Default command used when running `docker compose up`
    # download-data 
    # --userdir /freqtrade/user_data 
    # --config /freqtrade/user_data/config.json
    # --config /freqtrade/user_data/.secret_config.json
    # --pairs-file /freqtrade/user_data/data/binance/pairs.json 
    # --days 240 --trading-mode spot --exchange binance
    command: >

      trade 
      --userdir /freqtrade/user_data
      --config /freqtrade/user_data/config.json 
      --config /freqtrade/user_data/.secret_config.json 
      --strategy-path /freqtrade/user_data/strategies
      --strategy Strategy005 
      --logfile /freqtrade/user_data/logs/freqtrade.log 
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      -vvv

  freqtrade-mirel:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-mirel
    # user: "$UID:$GID"
    networks:
      skynet:
        ipv4_address: 172.22.0.52
    volumes:
      - "/home/cristian/Repositories/freqtrade/mirel:/freqtrade/user_data"
    ports:
      - "8090:8080"
    # Default command used when running `docker compose up`
    # download-data 
    # --userdir /freqtrade/user_data 
    # --config /freqtrade/user_data/config.json
    # --config /freqtrade/user_data/.secret_config.json
    # --pairs-file /freqtrade/user_data/data/binance/pairs.json 
    # --days 240 --trading-mode spot --exchange binance
    command: >

      trade 
      --userdir /freqtrade/user_data
      --config /freqtrade/user_data/config.json 
      --config /freqtrade/user_data/.secret_config.json 
      --strategy-path /freqtrade/user_data/strategies
      --strategy Strategy004 
      --logfile /freqtrade/user_data/logs/freqtrade.log 
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      -vvv
