networks:
  skynet:
    external: true

services:
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
     - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/cristian/Repositories/nginx/data:/data
      - /home/cristian/Repositories/nginx/letsencrypt:/etc/letsencrypt
#      - /home/cristian/Repositories/nginx/nginx:/etc/nginx
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nginx-pm"
      DB_MYSQL_PASSWORD: /run/secrets/db_pwd
      DB_MYSQL_NAME: "npm"
    networks:
      skynet:
        ipv4_address: 172.22.0.3
    # network_mode: host
    depends_on:
      - nginx-db

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 600s
      timeout: 3s
  nginx-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_pwd
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: "nginx-pm"
      MYSQL_PASSWORD: /run/secrets/db_pwd
    networks:
      skynet:
        ipv4_address: 172.22.0.4
    volumes:
      - /home/cristian/Repositories/nginx/mysql:/var/lib/mysql

secrets:
  db_root_pwd:
    file: /home/cristian/Repositories/nginx/secrets/db_pwd.txt
  db_pwd:
    file: /home/cristian/Repositories/nginx/secrets/db_root_pwd.txt