networks:
  skynet:
    external: true

volumes:
  nginx_data:
    name: nginx_data

services:
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: nginx
    network:
      skynet:
        ipv4_address: 172.22.0.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nginx_data:/data
      - nginx_data:/etc/letsencrypt