volumes:
  nginx_data:
    name: nginx_data

services:
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: nginx
    network_mode: host
    volumes:
      - nginx_data:/data
      - nginx_data:/etc/letsencrypt
  healthcheck:
    test: ["CMD", "/usr/bin/check-health"]
    interval: 10s
    timeout: 3s
